/**
 * Shelter API
 * A website which provides information about pets which are being sheltered and are available for adoption. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface HealthV1Results { 
    /**
     * The current status of the service's component.
     */
    status: HealthV1Results.StatusEnum;
    /**
     * A short description of this component's healthy.
     */
    description: string;
    data?: any;
}
export namespace HealthV1Results {
    export type StatusEnum = 'Healthy' | 'Degraded' | 'Unhealthy';
    export const StatusEnum = {
        Healthy: 'Healthy' as StatusEnum,
        Degraded: 'Degraded' as StatusEnum,
        Unhealthy: 'Unhealthy' as StatusEnum
    };
}