/**
 * Shelter API
 * A website which provides information about pets which are being sheltered and are available for adoption. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InquiryV1 { 
    /**
     * The unique ID of the inquiry in our database.
     */
    readonly id?: string;
    /**
     * The unique ID of the pet that this inquiry focuses upon.
     */
    petId: string;
    /**
     * The name of the individual making the inquiry.
     */
    name: string;
    /**
     * The email address of the individual making the inquiry.
     */
    email: string;
    /**
     * The message attached with the inquiry, allowing the individual to state their intent.
     */
    message?: string;
}