/**
 * Shelter API
 * A website which provides information about pets which are being sheltered and are available for adoption. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * An error describing a problem that the server has encountered or identified.
 */
export interface ModelError { 
    /**
     * The HTTP status code corresponding to this error.
     */
    status: BigInteger;
    /**
     * The human readable description of the HTTP status code.
     */
    title: string;
    /**
     * The URI describing the specific error or class of errors this belongs to.
     */
    type?: string;
    /**
     * A unique trace ID which can be used to associate this error with any corresponding logs.
     */
    traceId: string;
    /**
     * Additional information about the errors which occurred while processing the request.
     */
    errors?: any;
}