/**
 * Shelter API
 * A website which provides information about pets which are being sheltered and are available for adoption. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PetV1 { 
    /**
     * The unique ID of the pet in our database.
     */
    readonly id: string;
    /**
     * The pet's given name, used to call it for cuddles and petting.
     */
    name: string;
    /**
     * The current adoption status of the pet.
     */
    status?: PetV1.StatusEnum;
    /**
     * The kind of pet, might be a dog, cat or goldfish amongst others.
     */
    kind: PetV1.KindEnum;
    /**
     * The breed of the pet, whether a Golden Retriever or Russian Blue.
     */
    breed?: string;
    /**
     * A short description of the pet, may use Markdown for rich formatting.
     */
    description?: string;
    /**
     * The date on which the pet was born, used to determine when treats should be purchased.
     */
    birthday?: string;
    /**
     * A list of photographs of this pet to help warm hearts and put smiles on faces.
     */
    photos?: Array<string>;
}
export namespace PetV1 {
    export type StatusEnum = 'available' | 'adopted' | 'unavailable';
    export const StatusEnum = {
        Available: 'available' as StatusEnum,
        Adopted: 'adopted' as StatusEnum,
        Unavailable: 'unavailable' as StatusEnum
    };
    export type KindEnum = 'dog' | 'cat' | 'goldfish' | 'horse' | 'hamster';
    export const KindEnum = {
        Dog: 'dog' as KindEnum,
        Cat: 'cat' as KindEnum,
        Goldfish: 'goldfish' as KindEnum,
        Horse: 'horse' as KindEnum,
        Hamster: 'hamster' as KindEnum
    };
}